#!/usr/bin/env bash

*This script displays "To infinity and beyond" indefinitely and handles SIGTERM*

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
echo "To infinity and beyond"
sleep 2
done

#!/usr/bin/env bash

*This script stops the 7-highlander process*

PID=$(pgrep -f 7-highlander)
pkill -f 7-highlander
